[package]
name = "day-1-sonar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "part-1"
path = "src/part-1.rs"

[[bin]]
name = "part-2"
path = "src/part-2.rs"

[dependencies]
